<a href="https://colab.research.google.com/github/ngthvinhrai/KNNImputation_on_EPL_stat/blob/main/KNNImputation_on_EPL_Stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
stat = pd.read_csv("EPL_1st_Half_Stats.csv")

In [ ]:
stat.head()

HomeTeam          AwayTeam  HTotalShot  ATotalShot  HSoT  ASoT  HM  \
0        Liverpool           Norwich           6           7     4     2   1   
1  West Ham United   Manchester City           1           8     1     4   0   
2   Crystal Palace           Everton           3           6     0     1   0   
3          Burnley       Southampton           2           6     0     2   2   
4      Bournemouth  Sheffield United           3           4     0     2   3   

   AM  HBS  ABS  ...  APTB  HI  AI  HRes  ARes  HSave  ASave  1stHalfGoals  \
0   4    1    1  ...     7   4   6     3    20      2      1             4   
1   2    0    2  ...    12   5   6     7     9      3      1             1   
2   2    3    3  ...     6   5   6    15     8      1      0             0   
3   2    0    2  ...     4   9   8     3     8      2      0             0   
4   1    0    1  ...     4   7  10     6     7      2      0             0   

   1st15m  2nd15m  
0       0       1  
1       1       1  
2       0       0  
3       0       1  
4       0       1  

[5 rows x 27 columns]

In [ ]:
home = ['HTotalShot', 'HSoT', 'HM', 'HBS', 'HCK', 'HDP', 'HAccCrs', 'HPTB', 'HI', 'HRes', 'HSave']
away = ['ATotalShot', 'ASoT', 'AM', 'ABS', 'ACK', 'ADP', 'AAccCrs', 'APTB', 'AI', 'ARes', 'ASave']

In [ ]:
HStat = stat[home]
AStat = stat[away]

In [ ]:
AllStat = stat.drop(['HomeTeam', 'AwayTeam','1stHalfGoals', '1st15m', '2nd15m'], axis=1)

In [ ]:
AllStat.head()

HTotalShot  ATotalShot  HSoT  ASoT  HM  AM  HBS  ABS  HCK  ACK  ...  \
0           6           7     4     2   1   4    1    1    5    1  ...   
1           1           8     1     4   0   2    0    2    0    1  ...   
2           3           6     0     1   0   2    3    3    3    2  ...   
3           2           6     0     2   2   2    0    2    0    2  ...   
4           3           4     0     2   3   1    0    1    1    1  ...   

   HAccCrs  AAccCrs  HPTB  APTB  HI  AI  HRes  ARes  HSave  ASave  
0        4        1     8     7   4   6     3    20      2      1  
1        0        1     8    12   5   6     7     9      3      1  
2        1        3    11     6   5   6    15     8      1      0  
3        1        2    10     4   9   8     3     8      2      0  
4        0        2     6     4   7  10     6     7      2      0  

[5 rows x 22 columns]

In [ ]:
HStat.head()

HTotalShot  HSoT  HM  HBS  HCK  HDP  HAccCrs  HPTB  HI  HRes  HSave
0           6     4   1    1    5  6.0        4     8   4     3      2
1           1     1   0    0    0  1.0        0     8   5     7      3
2           3     0   0    3    3  3.0        1    11   5    15      1
3           2     0   2    0    0  1.0        1    10   9     3      2
4           3     0   3    0    1  3.0        0     6   7     6      2

In [ ]:
HStat[HStat['HDP'].isna()]

In [ ]:
HStat.dropna(axis='rows').drop('HDP', axis=1)

In [ ]:
AStat.head()

ATotalShot  ASoT  AM  ABS  ACK  ADP  AAccCrs  APTB  AI  ARes  ASave
0           7     2   4    1    1  7.0        1     7   6    20      1
1           8     4   2    2    1  7.0        1    12   6     9      1
2           6     1   2    3    2  4.0        3     6   6     8      0
3           6     2   2    2    2  2.0        2     4   8     8      0
4           4     2   1    1    1  4.0        2     4  10     7      0

In [ ]:
AllStat[AllStat['HDP'].isna()].drop(['HDP', 'ADP'], axis=1)

HTotalShot  ATotalShot  HSoT  ASoT  HM  AM  HBS  ABS  HCK  ACK  HAccCrs  \
9             5           8     2     3   2   4    1    1    1    1        1   
18            6           1     3     0   2   0    1    1    3    2        4   
21            4          10     4     4   0   1    0    5    0    4        0   
31            9           3     3     0   3   3    3    0    1    2        2   
43            1           6     0     3   1   1    0    2    0    3        2   
58            4           3     1     2   1   0    2    1    3    1        1   
66           17           0     4     0   4   0    9    0    3    0        2   
76            6           7     2     4   3   3    1    0    3    0        0   
81            5           3     2     0   2   2    1    1    3    0        2   
95            4           8     1     4   3   2    0    2    3    2        1   
107           5           7     1     5   2   1    2    1    1    4        3   
111          11           0     2     0   5   0    4    0    4    0        3   
127           9           6     2     2   5   3    2    1    2    1        3   
133          12           2     5     1   4   1    3    0    6    0        5   
143           9           3     4     2   3   0    2    1    3    3        4   
150           4           4     2     1   1   2    1    1    1    3        2   
163           9           4     2     1   3   0    4    3    5    2        6   
167           9           5     2     2   4   3    3    0    2    4        1   
178           2           8     0     2   2   4    0    2    0    4        1   
183           3           2     1     1   1   0    1    1    2    0        3   
197           5           3     2     1   3   2    0    0    2    1        2   
201           6           6     1     2   2   2    3    2    4    2        2   
216           7           5     4     3   1   1    2    1    7    2        2   
227           3           8     0     1   3   3    0    4    0    6        4   
235           9           0     3     0   3   0    3    0   10    3        5   
240           7           5     1     1   3   1    3    3    2    4        2   
258           7           6     0     1   4   3    3    2    3    4        1   
260           9           3     3     2   5   0    1    1    2    4        1   
266          10           3     4     2   3   0    3    1    4    0        3   
274           3           9     2     4   1   4    0    1    2    7        2   
287           6           1     5     0   1   1    0    0    1    0        1   

     AAccCrs  HPTB  APTB  HI  AI  HRes  ARes  HSave  ASave  
9          1     7    11   8   7    10     6      3      1  
18         0    17    15   3   7    12    13      0      2  
21         3     7    12   3   5    14     5      2      2  
31         1     5     5   7   6     6    12      0      1  
43         2     5    14   7   9     7    10      0      0  
58         1     3     4   8   5     3    10      0      1  
66         0     5    12   5   6     7    21      0      4  
76         1    12     3   3   6     5    11      1      0  
81         3    14     9   4   4     6    12      0      2  
95         1     5     6   7   7     9    10      2      1  
107        1     6    11   6   4    12     8      4      1  
111        0     7     9   4   6     3    14      0      2  
127        2     8     6   5  10     8    12      1      0  
133        2     3    12   9   5     6    12      1      5  
143        2     6    11   5   9    10    12      1      3  
150        4    17     7   6   2    10    10      1      1  
163        1     6     3   9   6    13    21      1      2  
167        2     5    11   2   6    14    13      2      2  
178        3    11     6   8   8    11     2      0      0  
183        1    12    14   5   3     4    13      0      1  
197        5     3     8   6   5     5     5      1      1  
201        2    11    16   4  10     2    15      0      1  
216        1     4     5   6   3     4   

In [ ]:
def nan_euclidean(x1, x2):
  weight = 1  # weight = no. of coordinates / no. of available coordinates
  dist = np.sqrt(np.sum((x1-x2)**2, axis=1))
  return dist

In [ ]:
def findmax(arr):
  max = arr[0]
  idx = 0
  for i in range(len(arr)):
    if arr[i]>max:
      max = arr[i]
      idx = i
  return max, idx

In [ ]:
def kmin(arr, k):
  temp = arr[0:k]
  pos = [i for i in range(0,k)]
  max, idx = findmax(temp)
  for i in range(k, len(arr)):
    if arr[i]<max:
      temp[idx] = arr[i]
      pos[idx] = i
      max, idx = findmax(temp)

  return temp, pos

In [ ]:
def KNNImputation(dataframe, k_neighbours):
  avPoint = dataframe.dropna(axis='rows').drop(['HDP', 'ADP'], axis=1).to_numpy()
  naPoint = dataframe[dataframe['HDP'].isna()].drop(['HDP', 'ADP'], axis=1).to_numpy()
  result = []
  for i in range(len(naPoint)):
    dist = nan_euclidean(naPoint[i], avPoint)
    topdist, pos = kmin(dist, k_neighbours)
    result.append([naPoint[i], topdist, pos])

  return avPoint, naPoint, result

In [ ]:
k_neighb = 3

In [ ]:
avPoint, naPoint, result = KNNImputation(AllStat, k_neighb)

In [ ]:
result[0][2]

[247, 287, 216]

In [ ]:
print(naPoint[0])
print(avPoint[result[0][2]])

[ 5  8  2  3  2  4  1  1  1  1  1  1  7 11  8  7 10  6  3  1]
[[ 4  8  2  2  2  3  0  3  1  3  2  2  7 10  6  4  8  6  1  1]
 [ 4  8  3  1  1  5  0  2  0  3  2  3  7 11 10  6  7  8  1  2]
 [ 6  7  2  4  3  1  1  2  1  2  1  4  7 10  6  3 10  5  2  0]]


In [ ]:
AllStat.dropna(axis='rows').iloc[result[0][2]][['HDP', 'ADP']]

HDP  ADP
277  2.0  6.0
318  4.0  6.0
242  5.0  4.0

In [ ]:
DPStat = AllStat.dropna(axis='rows')[['HDP', 'ADP']].to_numpy()
DPStat[result[0][2]]

array([[2., 6.],
       [4., 6.],
       [5., 4.]])

In [ ]:
for i in range(len(result)):
  print(np.sum(DPStat[result[i][2]], axis=0)/k_neighb)

[3.66666667 5.33333333]
[4.66666667 1.33333333]
[3.33333333 5.        ]
[5.33333333 1.        ]
[2.33333333 5.66666667]
[2.33333333 2.66666667]
[10.66666667  0.66666667]
[3.         3.33333333]
[3.66666667 1.66666667]
[3.         5.33333333]
[2.33333333 2.66666667]
[4.33333333 1.33333333]
[7.         2.66666667]
[7.66666667 2.33333333]
[5.33333333 2.        ]
[3.33333333 3.66666667]
[6.33333333 2.66666667]
[7.         5.66666667]
[1.         6.33333333]
[4.         1.66666667]
[3.33333333 2.        ]
[4.66666667 3.33333333]
[4.33333333 3.33333333]
[3.66666667 5.66666667]
[6.         3.66666667]
[4.33333333 4.        ]
[6.33333333 3.        ]
[6.33333333 4.        ]
[6.33333333 2.66666667]
[3.66666667 6.33333333]
[5.66666667 1.        ]
